# Generated by Django 3.1.2 on 2021-07-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproductmodel',
            name='piece',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Adet (Canlı Stok)'),
        ),
        migrations.AlterField(
            model_name='costdetailmodel',
            name='piece',
            field=models.PositiveIntegerField(verbose_name='Adet'),
        ),
    ]
