# Generated by Django 3.1.2 on 2020-11-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20201120_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproductmodel',
            name='barcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Barkod'),
        ),
    ]
