# Generated by Django 3.1.2 on 2021-04-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='İsim')),
                ('taxId', models.CharField(blank=True, max_length=255, null=True, verbose_name='TC No / Vergi No')),
                ('mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='E-Posta')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='İl')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='İlçe')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Adres Bilgisi')),
            ],
        ),
    ]
