# Generated by Django 3.1.2 on 2021-04-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20210416_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='İlçe'),
        ),
    ]
