# Generated by Django 3.1.2 on 2021-04-15 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('hepsiburada_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HepsiOrderDetailModel',
            fields=[
                ('marketorderdetailmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketplace.marketorderdetailmodel')),
                ('totalHbDiscount', models.FloatField(verbose_name='Toplam HB İndirimi')),
                ('priceToBilling', models.FloatField(verbose_name='Faturalandırılacak Tutar')),
                ('comissionRate', models.FloatField(blank=True, null=True, verbose_name='Komisyon Oranı')),
                ('comission', models.FloatField(blank=True, null=True, verbose_name='Komisyon Tutarı(KDV Dahil)')),
                ('recoupByHB', models.FloatField(blank=True, null=True, verbose_name="HB'nin Karşıladığı Kampanya Tutarı")),
                ('billToHb', models.FloatField(blank=True, null=True, verbose_name="HB'ye Faturalandırılacak")),
            ],
            bases=('marketplace.marketorderdetailmodel',),
        ),
        migrations.CreateModel(
            name='HepsiOrderModel',
            fields=[
                ('marketordermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketplace.marketordermodel')),
            ],
            bases=('marketplace.marketordermodel',),
        ),
        migrations.CreateModel(
            name='HepsiPaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ödeme Tarihi')),
                ('incomingAmount', models.FloatField(verbose_name='Gelen Tutar')),
                ('amountToCome', models.FloatField(verbose_name='Gelmesi Gereken Tutar')),
            ],
        ),
        migrations.CreateModel(
            name='HepsiProductModel',
            fields=[
                ('marketproductmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketplace.marketproductmodel')),
                ('DispatchTime', models.IntegerField(verbose_name='Kargoya Verilme Süresi')),
                ('CargoCompany1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kargo Firması 1')),
                ('CargoCompany2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kargo Firması 2')),
                ('CargoCompany3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kargo Firması 3')),
            ],
            bases=('marketplace.marketproductmodel',),
        ),
        migrations.CreateModel(
            name='UpdateStatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Tarih')),
                ('control_id', models.CharField(max_length=200, verbose_name='Kontrol ID')),
            ],
        ),
        migrations.AddField(
            model_name='hepsibillmodel',
            name='hodm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hepsiburada_api.hepsiorderdetailmodel'),
        ),
        migrations.AddField(
            model_name='hepsibillmodel',
            name='hom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hepsiburada_api.hepsiordermodel'),
        ),
        migrations.AddField(
            model_name='hepsibillmodel',
            name='hpm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hepsiburada_api.hepsipaymentmodel'),
        ),
    ]
