# Generated by Django 3.1.2 on 2021-07-23 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hepsiburada_api', '0002_auto_20210415_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hepsiorderdetailmodel',
            name='comissionRate',
        ),
    ]
