# Generated by Django 3.1.2 on 2021-06-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WixAuthTokensModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshToken', models.CharField(max_length=500, verbose_name='Refresh Token')),
                ('authToken', models.CharField(max_length=500, verbose_name='Auth Token')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Token Alma Tarihi')),
            ],
        ),
    ]
