# Generated by Django 3.1.2 on 2021-06-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wixauthtokensmodel',
            name='authToken',
            field=models.CharField(max_length=1000, verbose_name='Auth Token'),
        ),
        migrations.AlterField(
            model_name='wixauthtokensmodel',
            name='refreshToken',
            field=models.CharField(max_length=1000, verbose_name='Refresh Token'),
        ),
    ]
