# Generated by Django 3.1.2 on 2021-06-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix_api', '0002_auto_20210606_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wixauthtokensmodel',
            name='authToken',
            field=models.TextField(max_length=3000, verbose_name='Auth Token'),
        ),
        migrations.AlterField(
            model_name='wixauthtokensmodel',
            name='refreshToken',
            field=models.CharField(max_length=499, verbose_name='Refresh Token'),
        ),
    ]
