# Generated by Django 3.1.2 on 2021-06-11 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_auto_20210505_0024'),
        ('wix_api', '0003_auto_20210607_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='WixProductModel',
            fields=[
                ('marketproductmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketplace.marketproductmodel')),
            ],
            bases=('marketplace.marketproductmodel',),
        ),
    ]
