# Generated by Django 3.1.2 on 2021-06-14 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_auto_20210614_1848'),
        ('wix_api', '0004_wixproductmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WixOrderDetailModel',
            fields=[
                ('marketorderdetailmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketplace.marketorderdetailmodel')),
            ],
            bases=('marketplace.marketorderdetailmodel',),
        ),
        migrations.CreateModel(
            name='WixProductUpdateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeQuantity', models.IntegerField(verbose_name='Değişim Miktarı')),
                ('updated', models.BooleanField(default=False, verbose_name='Güncellendi Mi?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wix_api.wixproductmodel')),
            ],
        ),
    ]
