# Generated by Django 3.1.2 on 2021-06-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix_api', '0005_wixorderdetailmodel_wixproductupdatemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wixproductmodel',
            name='variantId',
            field=models.CharField(default='', max_length=100, verbose_name='Varyant ID'),
            preserve_default=False,
        ),
    ]
