# Generated by Django 3.1.2 on 2021-04-15 23:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketType', models.CharField(blank=True, choices=[('hepsiburada', 'Hepsiburada'), ('trendyol', 'Trendyol')], max_length=255, null=True, verbose_name='Pazar yeri')),
                ('customerName', models.CharField(max_length=200, verbose_name='Müşteri Adı')),
                ('orderNumber', models.CharField(max_length=100, verbose_name='Sipariş No')),
                ('packageNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Paket Numarası')),
                ('orderDate', models.DateTimeField(verbose_name='Sipariş Tarihi')),
                ('deliveryDate', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('totalPrice', models.FloatField(blank=True, null=True, verbose_name='Toplam Tutar')),
                ('priceToBilling', models.FloatField(blank=True, null=True, verbose_name='Faturalandırılacak Tutar')),
                ('orderStatus', models.CharField(blank=True, choices=[('Awaiting', 'Ödeme Onayı Bekleniyor'), ('ReadyToShip', 'Gönderime Hazır'), ('Picking', 'Paket Hazırlanıyor'), ('Invoiced', 'Fatura Kesildi'), ('Shipped', 'Taşıma Durumunda'), ('AtCollectionPoint', 'PUDO Noktasında'), ('Cancelled', 'İptal Edildi'), ('UnPacked', 'Paketi Bölünmüş'), ('Delivered', 'Teslim Edildi'), ('UnDelivered', 'Müşteriye Ulaştırılmadı'), ('UnDeliveredAndReturned', 'Ulaştırılamadı ve Geri Döndü')], max_length=255, null=True, verbose_name='Siparişin Durumu')),
            ],
        ),
        migrations.CreateModel(
            name='MarketProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketType', models.CharField(blank=True, choices=[('hepsiburada', 'Hepsiburada'), ('trendyol', 'Trendyol')], max_length=255, null=True, verbose_name='Pazar yeri')),
                ('productName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ürün Adı')),
                ('marketplaceSku', models.CharField(max_length=100, verbose_name='Pazaryeri SKU')),
                ('sellerSku', models.CharField(max_length=100, verbose_name='Satıcı SKU')),
                ('salePrice', models.FloatField(verbose_name='Satış Fiyatı')),
                ('onSale', models.BooleanField(verbose_name='Satılabilir mi?')),
                ('availableStock', models.IntegerField(verbose_name='Mevcut Stok')),
                ('lastControlDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Son BuyBox Kontrol Tarihi')),
                ('buyBoxRank', models.IntegerField(blank=True, null=True, verbose_name='Buybox Sıralaması')),
                ('productLink', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='MarketUpdateQueueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('isUpdated', models.BooleanField(default=False, verbose_name='Güncellendi mi?')),
                ('mpm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketproductmodel', verbose_name='Pazaryeri Ürünü')),
            ],
        ),
        migrations.CreateModel(
            name='MarketProductBuyBoxListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Sıralama')),
                ('merchantName', models.CharField(max_length=255, verbose_name='Satıcı Adı')),
                ('price', models.FloatField(verbose_name='Satıcının Fiyatı')),
                ('dispatchTime', models.IntegerField(blank=True, null=True, verbose_name='Kargoya Verme Süresi')),
                ('mpm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketproductmodel', verbose_name='Pazaryeri Ürünü')),
            ],
        ),
        migrations.CreateModel(
            name='MarketOrderDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.FloatField(blank=True, null=True, verbose_name='Tutar')),
                ('quantity', models.IntegerField(verbose_name='Adet')),
                ('mom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketordermodel', verbose_name='Sipariş Modeli')),
                ('mpm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketproductmodel', verbose_name='Market Ürünü')),
            ],
        ),
        migrations.CreateModel(
            name='MarketMedProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSalable', models.BooleanField(verbose_name='Satılabilir mi?')),
                ('mpm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketproductmodel', verbose_name='Pazaryeri Ürünü')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.productmodel', verbose_name='Bağlı Ürün')),
            ],
        ),
    ]
