# Generated by Django 3.1.2 on 2021-04-15 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketordermodel',
            name='customerModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.customermodel'),
        ),
    ]
