# Generated by Django 3.1.2 on 2021-04-15 23:53

from django.db import migrations

def transfer_customer(apps, schema_editor):
    customerModel = apps.get_model('billing', 'CustomerModel')
    marketOrderModel = apps.get_model('marketplace', 'MarketOrderModel')

    for order in marketOrderModel.objects.all():
        customer, created = customerModel.objects.get_or_create(name=order.customerName)
        order.customerModel = customer
        order.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_marketordermodel_customermodel'),
    ]

    operations = [
        migrations.RunPython(transfer_customer),
    ]
