# Generated by Django 3.1.2 on 2021-04-16 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('marketplace', '0003_auto_20210415_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketordermodel',
            name='customerModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.customermodel'),
        ),
    ]
