# Generated by Django 3.1.2 on 2021-04-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20210416_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketordermodel',
            name='customerName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Müşteri Adı'),
        ),
    ]
