# Generated by Django 3.1.2 on 2021-04-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_marketbuyboxtracemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbuyboxtracemodel',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
    ]
