# Generated by Django 3.1.2 on 2021-04-25 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_auto_20210420_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketproductbuyboxlistmodel',
            name='uncomp',
            field=models.BooleanField(default=False, verbose_name='Rekabet edilemez?'),
        ),
        migrations.CreateModel(
            name='MarketOrderPredCostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costType', models.CharField(choices=[('Shipment', 'Kargo'), ('Comission', 'Komisyon'), ('PurchasePrice', 'Alım Fiyatı'), ('Extra', 'Ekstra')], max_length=255, verbose_name='Gider Türü')),
                ('costAmount', models.FloatField(verbose_name='Tutar')),
                ('modm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketorderdetailmodel', verbose_name='Sipariş Detay Modeli')),
                ('mom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketordermodel', verbose_name='Sipariş Modeli')),
            ],
        ),
    ]
