# Generated by Django 3.1.2 on 2021-04-25 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0011_auto_20210425_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMarketPlaceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketType', models.CharField(choices=[('hepsiburada', 'Hepsiburada'), ('trendyol', 'Trendyol')], max_length=255, verbose_name='Market Tipi')),
                ('supplierId', models.CharField(max_length=255, verbose_name='Trendyol Satıcı ID / Hepsiburada Merchant ID')),
                ('apiKey', models.CharField(blank=True, max_length=255, null=True, verbose_name='Trednyol Satıcı ApiKey')),
                ('apiSecret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Trednyol Satıcı ApiSecret')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMarketShipmentRuleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minPrice', models.FloatField(verbose_name='Min Fiyat')),
                ('maxPrice', models.FloatField(verbose_name='Max Fiyat')),
                ('cost', models.FloatField(verbose_name='Kargo Tutarı')),
                ('marketType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.usermarketplacemodel')),
            ],
        ),
    ]
