# Generated by Django 3.1.2 on 2021-04-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_auto_20210425_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketproductmodel',
            name='userMarket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.usermarketplacemodel', verbose_name='Pazar Yeri'),
        ),
        migrations.AlterField(
            model_name='usermarketplacemodel',
            name='apiKey',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Trendyol Satıcı ApiKey'),
        ),
        migrations.AlterField(
            model_name='usermarketplacemodel',
            name='apiSecret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Trendyol Satıcı ApiSecret'),
        ),
    ]
