# Generated by Django 3.1.2 on 2021-04-25 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_auto_20210425_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketordermodel',
            name='userMarket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.usermarketplacemodel', verbose_name='Pazar Yeri'),
        ),
    ]
