# Generated by Django 3.1.2 on 2021-04-25 17:14

from django.db import migrations

def customMig(apps, schema_editor):
    marketOrderModel = apps.get_model('marketplace', 'MarketOrderModel')
    userMaketPlaceModel = apps.get_model('marketplace', 'UserMarketPlaceModel').objects.all()

    for mp in marketOrderModel.objects.all():
        ump = userMaketPlaceModel.get(marketType=mp.marketType)
        mp.userMarket = ump
        mp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_marketordermodel_usermarket'),
    ]

    operations = [
        migrations.RunPython(customMig),
    ]
