# Generated by Django 3.1.2 on 2021-04-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_auto_20210425_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermarketshipmentrulemodel',
            old_name='marketType',
            new_name='userMarket',
        ),
        migrations.RemoveField(
            model_name='marketordermodel',
            name='marketType',
        ),
        migrations.RemoveField(
            model_name='marketproductmodel',
            name='marketType',
        ),
    ]
