# Generated by Django 3.1.2 on 2021-04-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_auto_20210425_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermarketplacemodel',
            name='apiKey',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Trendyol / N11 Satıcı ApiKey'),
        ),
        migrations.AlterField(
            model_name='usermarketplacemodel',
            name='apiSecret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Trendyol / N11 Satıcı ApiSecret'),
        ),
        migrations.AlterField(
            model_name='usermarketplacemodel',
            name='marketType',
            field=models.CharField(choices=[('hepsiburada', 'Hepsiburada'), ('trendyol', 'Trendyol'), ('nonbir', 'N11')], max_length=255, verbose_name='Market Tipi'),
        ),
        migrations.AlterField(
            model_name='usermarketplacemodel',
            name='supplierId',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Trendyol Satıcı ID / Hepsiburada Merchant ID'),
        ),
    ]
