# Generated by Django 3.1.2 on 2021-04-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_auto_20210428_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketproductbuyboxlistmodel',
            name='oldPrice',
            field=models.FloatField(default=0, verbose_name='Satıcının Önceki Fiyatı'),
            preserve_default=False,
        ),
    ]
