# Generated by Django 3.1.2 on 2021-05-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_marketproductbuyboxlistmodel_oldprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermarketplacemodel',
            name='marketType',
            field=models.CharField(choices=[('hepsiburada', 'Hepsiburada'), ('trendyol', 'Trendyol'), ('n11', 'N11')], max_length=255, verbose_name='Market Tipi'),
        ),
    ]
