# Generated by Django 3.1.2 on 2021-06-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_auto_20210614_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermarketplacemodel',
            name='marketType',
            field=models.CharField(choices=[('hepsiburada', 'Hepsiburada'), ('trendyol', 'Trendyol'), ('n11', 'N11'), ('wix', 'Wix'), ('cicek', 'Çiçek Sepeti')], max_length=255, verbose_name='Market Tipi'),
        ),
    ]
