# Generated by Django 3.1.2 on 2021-07-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_marketordermodel_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermarketshipmentrulemodel',
            name='cargo',
            field=models.CharField(blank=True, choices=[('hepsi', 'HepsiJet'), ('aras', 'Aras Kargo'), ('surat', 'Sürat Kargo')], max_length=255, null=True, verbose_name='Kargo Firması'),
        ),
    ]
