# Generated by Django 3.1.2 on 2021-07-23 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_auto_20210709_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketproductmodel',
            name='commissionRate',
        ),
        migrations.AddField(
            model_name='marketorderdetailmodel',
            name='comissionRate',
            field=models.FloatField(blank=True, null=True, verbose_name='Komisyon Oranı'),
        ),
        migrations.CreateModel(
            name='MarketProductCommissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('endDate', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('commissionRate', models.FloatField(verbose_name='Komisyon Oranı')),
                ('mpm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketproductmodel', verbose_name='Ürün')),
            ],
        ),
    ]
