# Generated by Django 3.1.2 on 2021-07-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_auto_20210723_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketorderdetailmodel',
            name='comissionRate',
            field=models.FloatField(default=0, verbose_name='Komisyon Oranı'),
        ),
    ]
