# Generated by Django 3.2.8 on 2021-10-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_auto_20210723_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbuyboxtracemodel',
            name='giveMax',
            field=models.BooleanField(default=False, verbose_name='Rakip yoksa veya rekabet edilemiyorsa max(true)/min(false) fiyatı ver?'),
        ),
        migrations.AddField(
            model_name='marketbuyboxtracemodel',
            name='recoMax',
            field=models.BooleanField(default=False, verbose_name='Max fiyatı tanı(true)/ma(false)?'),
        ),
    ]
