# Generated by Django 3.2.8 on 2021-10-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0030_auto_20211009_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketproductbuyboxlistmodel',
            name='uncomp',
        ),
        migrations.AddField(
            model_name='marketproductbuyboxlistmodel',
            name='isCompeted',
            field=models.BooleanField(default=False, verbose_name='Rekabet edildi mi?'),
        ),
    ]
