# Generated by Django 3.2.8 on 2021-12-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0031_auto_20211009_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketbuyboxtracemodel',
            name='isActive',
            field=models.BooleanField(verbose_name='Aktif mi?'),
        ),
    ]
