# Generated by Django 4.0.1 on 2022-01-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0033_marketorderdetailmodel_sapnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketproductmodel',
            name='commissionRate',
            field=models.FloatField(default=0, verbose_name='Komisyon Oranı'),
        ),
    ]
