# Generated by Django 3.1.2 on 2021-06-18 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0022_auto_20210614_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicekProductModel',
            fields=[
                ('marketproductmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketplace.marketproductmodel')),
            ],
            bases=('marketplace.marketproductmodel',),
        ),
    ]
