# Generated by Django 3.1.2 on 2021-06-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicekproductmodel',
            name='listPrice',
            field=models.FloatField(default=0, verbose_name='Liste Fiyatı'),
            preserve_default=False,
        ),
    ]
