# Generated by Django 3.1.2 on 2021-04-15 23:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NProdctModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='SKU')),
                ('title', models.CharField(max_length=500, verbose_name='Ürün Adı')),
                ('subtitle', models.CharField(max_length=65, verbose_name='Alt Başlık')),
                ('description', ckeditor.fields.RichTextField(max_length=1000, verbose_name='Açıklama')),
                ('category', models.BigIntegerField(verbose_name='Kategori ID')),
                ('price', models.FloatField(verbose_name='Fiyat')),
                ('preparingDay', models.IntegerField(verbose_name='Ürün Hazırlanma Süresi(Gün)')),
                ('shipmentTemplate', models.CharField(max_length=255, verbose_name='Teslimat Şablon Adı')),
                ('quantity', models.IntegerField(verbose_name='Stok Miktarı')),
            ],
        ),
        migrations.CreateModel(
            name='NUpdateQueueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('npm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonbir_api.nprodctmodel', verbose_name='N11 Ürünü')),
            ],
        ),
    ]
