# Generated by Django 3.1.2 on 2021-04-28 19:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_auto_20210425_1733'),
        ('nonbir_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NProductModel',
            fields=[
                ('marketproductmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketplace.marketproductmodel')),
                ('subtitle', models.CharField(max_length=65, verbose_name='Alt Başlık')),
                ('description', ckeditor.fields.RichTextField(max_length=1000, verbose_name='Açıklama')),
                ('category', models.BigIntegerField(verbose_name='Kategori ID')),
                ('currencyType', models.CharField(choices=[('1', 'TL'), ('2', 'USD'), ('3', 'EUR')], max_length=255, verbose_name='Para Birimi')),
                ('productCondition', models.CharField(choices=[('1', 'Yeni'), ('2', '2. El')], max_length=255, verbose_name='Ürün Durumu')),
                ('preparingDay', models.IntegerField(verbose_name='Ürün Hazırlanma Süresi(Gün)')),
                ('shipmentTemplate', models.CharField(max_length=255, verbose_name='Teslimat Şablon Adı')),
            ],
            bases=('marketplace.marketproductmodel',),
        ),
        migrations.CreateModel(
            name='NProductImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ürün Linki')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ürün Resmi')),
                ('order', models.IntegerField(verbose_name='Gösterme Sırası')),
                ('nProductModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonbir_api.nproductmodel')),
            ],
        ),
        migrations.AlterField(
            model_name='nupdatequeuemodel',
            name='npm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonbir_api.nproductmodel', verbose_name='N11 Ürünü'),
        ),
        migrations.DeleteModel(
            name='NProdctModel',
        ),
    ]
