# Generated by Django 3.1.2 on 2021-05-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonbir_api', '0002_auto_20210428_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nproductimagemodel',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Resim Linki'),
        ),
        migrations.AlterField(
            model_name='nproductmodel',
            name='shipmentTemplate',
            field=models.CharField(choices=[('Aras Mağaza Öder', 'Aras Mağaza Öder'), ('Deneme', 'Deneme')], max_length=255, verbose_name='Teslimat Şablon Adı'),
        ),
    ]
