# Generated by Django 3.1.2 on 2021-06-04 01:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_auto_20210505_0024'),
        ('nonbir_api', '0004_nproductmodel_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOrderModel',
            fields=[
                ('marketordermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketplace.marketordermodel')),
            ],
            bases=('marketplace.marketordermodel',),
        ),
        migrations.AlterField(
            model_name='nproductmodel',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=2500, verbose_name='Açıklama'),
        ),
    ]
