# Generated by Django 3.1.2 on 2021-06-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonbir_api', '0005_auto_20210604_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='nproductmodel',
            name='n11CatalogId',
            field=models.CharField(default='', max_length=255, verbose_name='N11 Katalog Id'),
            preserve_default=False,
        ),
    ]
