# Generated by Django 3.1.2 on 2021-06-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonbir_api', '0006_nproductmodel_n11catalogid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nproductmodel',
            name='n11CatalogId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='N11 Katalog Id'),
        ),
    ]
