# Generated by Django 3.1.2 on 2021-06-05 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nonbir_api', '0007_auto_20210604_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='NProductDiscountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, verbose_name='İndirim Türü')),
                ('value', models.FloatField(verbose_name='İndirim Miktarı')),
                ('npm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonbir_api.nproductmodel', verbose_name='N11 Ürünü')),
            ],
        ),
    ]
