# Generated by Django 3.1.2 on 2021-06-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonbir_api', '0008_nproductdiscountmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='nproductmodel',
            name='displayPrice',
            field=models.FloatField(default=0, verbose_name='Fatura Fiyatı'),
            preserve_default=False,
        ),
    ]
