# Generated by Django 3.1.2 on 2021-06-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLoggingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorType', models.CharField(max_length=100, verbose_name='Hata Türü')),
                ('errorLocation', models.CharField(max_length=100, verbose_name='Hata Konumu')),
                ('errorMessage', models.TextField(max_length=1000, verbose_name='Hata Mesajı')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('isReported', models.BooleanField(default=False, verbose_name='Bildirildi mi')),
            ],
        ),
    ]
